### ISSUE TITLE
accessing _cachedSystemAnimationFence requires the main thread

### ISSUE THREAD

**Issue by yulichandra** [yahoo/YangMingShan#10]
I got error like [Error Log.txt](https://github.com/yahoo/YangMingShan/files/417635/Error.Log.txt).

Case : 
- Take Picture from Camera
- Single Picture pick

I just implement it using `yms_presentAlbumPhotoViewWithDelegate` like your example

**Comment by ZZBHuang** [comment]
Thanks for your feedback! Could you tell me what did you put inside 
> photoPickerViewController:didFinishPickingImage:
? This [link](http://stackoverflow.com/questions/32725926/nsinternalinconsistencyexception-accessing-cachedsystemanimationfence-requires) below may can help

**Comment by yulichandra** [comment]
Ya, thanks i already solve it. I think because `PHPhotoLibrary performChanges completionHandler` still in run in background and the picker dismiss it. 

solve it :
`[self performSelectorOnMainThread:@selector(didFinishPickingImage:) withObject:image waitUntilDone:YES];`

`
-(void)didFinishPickingImage:(UIImage*)image{
    [self.delegate photoPickerViewController:self didFinishPickingImage:image];
}
`

**Comment by ZZBHuang** [comment]
Great!
