### ISSUE TITLE
Selected cell count increase once more problem

### ISSUE THREAD

**Issue by Zener17** [yahoo/YangMingShan#17]
HI :) , Thanks for your source code, in use, I found a problem
1. First select a cell, and then just press the selected cell, open (YMSSinglePhotoViewController.m)
2. Click navigationItem.rightBarButtonItem@selector (selectCurrentPhoto :), after the previously selected cell count will increase once more
3. I think maybe need (YMSPhotoPickerViewController.m) function - (BOOL) collectionView: (UICollectionView *) collectionView shouldSelectItemAtIndexPath: (NSIndexPath *) indexPath, add a condition
if (cell.isSelected == YES) {
    return NO;
}

Sorry, my english is poor..... ㄒ_ㄒ

**Comment by ZZBHuang** [comment]
Thanks for your feedback! We'll fix it soon.
