### ISSUE TITLE
Not dismiss after take photo from camera.

### ISSUE THREAD

**Issue by tranngoclinh88** [yahoo/YangMingShan#21]
Happen in:
- iOS 8.4

Steps:
1. Open photo picker.
2. Select camera.
3. Take picture.
4. Press use photo => Nothing happen.

I found that delegate
- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingImage:(UIImage *)image editingInfo:(nullable NSDictionary<NSString *,id> *)editingInfo;
not called.

It called delegate:
- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary<NSString *,id> *)info {}

Please check!

**Comment by ZZBHuang** [comment]
@tranngoclinh88 Hi, could you tell me how you open the photo picker? I tried the demo app about taking a photo with default settings, it worked fine.

**Comment by stewwu** [comment]
We got it. the method is deprecated since iOS 3 but still available for a long time. We'll fix it. Thanks
(https://developer.apple.com/reference/uikit/uiimagepickercontrollerdelegate?language=objc)

**Comment by sagar-vaholiya** [comment]
Hi,

First of all, thanks for this amazing library.👍🏼

iOS 10.3 app crash after taking photo using camera. It works fine while taking photo from gallery.
Why it's not working for both. **I implemented it as Demo project**. 
![screen shot 2017-05-15 at 12 06 55 am](https://cloud.githubusercontent.com/assets/10954272/26036809/d48c4ddc-3902-11e7-86e7-fed62662058e.png)
