### ISSUE TITLE
 can we use for video same as image with this libary?

### ISSUE THREAD

**Issue by ruchiteasternts17Dec** [yahoo/YangMingShan#37]
I want to pick multiple videos and record video, is it possible for this library ?

**Comment by arjavlad** [comment]
@ruchiteasternts17Dec  use this fork [https://github.com/ink-spot/YangMingShan](https://github.com/ink-spot/YangMingShan)

**Comment by ruchiteasternts17Dec** [comment]
Thanks, its really helpful to me.
